"""create task table

Revision ID: ef0f372961ac
Revises: 6327eb4f9a50
Create Date: 2026-03-26 14:53:51.622699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef0f372961ac'
down_revision: Union[str, Sequence[str], None] = '6327eb4f9a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Создаем Enum типы
    op.execute("CREATE TYPE taskpriority AS ENUM ('VERY_URGENT', 'URGENT', 'CAN_WAIT', 'NOT_URGENT')")
    op.execute("CREATE TYPE taskstatus AS ENUM ('IN_PROGRESS', 'COMPLETED')")

    # Создаем таблицу с Enum полями
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('priority',
                              postgresql.ENUM('VERY_URGENT', 'URGENT', 'CAN_WAIT', 'NOT_URGENT', name='taskpriority',
                                              create_type=False), nullable=False, server_default='NOT_URGENT'),
                    sa.Column('status',
                              postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='taskstatus', create_type=False),
                              nullable=False, server_default='IN_PROGRESS'),
                    sa.Column('deadline', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('assignee_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем таблицу
    op.drop_table('tasks')

    # Удаляем Enum типы
    op.execute("DROP TYPE IF EXISTS taskpriority")
    op.execute("DROP TYPE IF EXISTS taskstatus")


# """create task table
#
# Revision ID: ef0f372961ac
# Revises: 6327eb4f9a50
# Create Date: 2026-03-26 14:53:51.622699
#
# """
# from typing import Sequence, Union
#
# from alembic import op
# import sqlalchemy as sa
#
#
# # revision identifiers, used by Alembic.
# revision: str = 'ef0f372961ac'
# down_revision: Union[str, Sequence[str], None] = '6327eb4f9a50'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None
#
#
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('tasks',
#     sa.Column('title', sa.String(length=100), nullable=False),
#     sa.Column('description', sa.Text(), nullable=True),
#     sa.Column('priority', sa.String(length=100), nullable=False),
#     sa.Column('status', sa.String(length=100), nullable=False),
#     sa.Column('deadline', sa.DateTime(), nullable=False),
#     sa.Column('created_at', sa.DateTime(), nullable=False),
#     sa.Column('updated_at', sa.DateTime(), nullable=True),
#     sa.Column('author_id', sa.Integer(), nullable=False),
#     sa.Column('assignee_id', sa.Integer(), nullable=False),
#     sa.Column('project_id', sa.Integer(), nullable=False),
#     sa.Column('category_id', sa.Integer(), nullable=False),
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
#     sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
#     sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
#     sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('tasks')
#     # ### end Alembic commands ###
